main: de.trekki03.trekkisinventorymanager.Main

name: TrekkisInventoryManager
author: Trekki03
description: The plugin contains inventory management for administrators and backpacks / team backpacks for normal users.

version: 1.0.0

commands:
  saveinv:
    usage: /saveinv [Online Player]
    description: Saves the players inventory content in a .yml file
    permission: tim.save
    permission-message: You need the permission tim.save

  loadinv:
    usage: /loadinv [Saved Player] [replace inventory (True/False)]
    description: Loads the players inventory content from a file. You can choose if your inventory gets replaced or if the content gets shown in an interface
    permission: tim.load
    permission-message: You need the permission tim.load

  seeinv:
    usage: /seeinv <Online Player> [interact true/false]
    description: Let you see and interact with the targets inventory.
    permission: tim.see
    permission-message: You need the permission tim.see

  seeend:
    usage: /seeend <Online Player> [interact true/false]
    description: Let you see and interact with the targets enderchest.
    permission: tim.end
    permission-message: You need the permission tim.end


permissions:
  tim.save:
    description: Allows usage of /saveinv command
    default: op

  tim.load:
    description: Allows usage of /loadinv command
    default: op

  tim.see:
    description: Allows usage of /seeinv command
    default: op

  tim.end:
    description: Allows usage of /seeend command
    default: op

  tim.*:
    description: Allows access to all permissions
    default: op
    children:
      tim.load: true
      tim.save: true
      tim.see: true
      tim.end: true